### ISSUE TITLE
A couple words about versioning

### ISSUE THREAD

**Issue by nervgh** [redblobgames/circular-obstacle-pathfinding#1]
Good day time!

[Here](https://github.com/redblobgames/circular-obstacle-pathfinding/blob/master/index.html#L942) you use latest version of Vue. The unpkg's [documentation](https://unpkg.com/#/) says 

> You may also use a tag or version range instead of a fixed version number, **or omit the version/tag entirely to use the latest tag**

It could cause some problems in the future when the [major version](http://semver.org/) of library will be changed. In other words, it could break your page when Vue will change its API.

I would be recommend to constraint the major version at least.

Best regards, 
Alex

**Comment by redblobgames** [comment]
@nervgh good point! Would you suggest using `https://unpkg.com/vue@2.x/dist/vue.min.js`?

**Comment by nervgh** [comment]
@redblobgames I prefer to denote the version exactly `https://unpkg.com/vue@^2.2.1/dist/vue.min.js`. It really means `https://unpkg.com/vue@2.x.x/dist/vue.min.js` but allows you to recognize what version was when you've been started using this package (library/framework/dependency).

https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by redblobgames** [comment]
Thanks!
